### ISSUE TITLE
转账只给对方加钱 不扣钱 且不收金额限制

### ISSUE THREAD

**Issue by chenshupe** [LiteLDev/LLMoney#4]
ll 2.16.2
bds 1.23.30
无任何插件模组 纯净端 使用moneypay命令转账 只给对方加钱 己方不扣除金币  且金额不受已有金币数量限制 可以转账任意金额

**Comment by ShrBox** [comment]
LiteLoaderBDS 2.16.0 - 2.16.2中附带的LLMoney版本为2.15.0，后续我会将LiteLoaderBDS Release中的文件进行替换，也可以直接从本仓库的Release中下载最新的构建
